sudo: required
dist: trusty
before_install:
  - ./build/build.sh
  - ./tests/test_setup.sh
  - ./tests/install.sh
language: python
install:
  - ideam install
  - ideam start
script:
  - python ./tests/pytest.py
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database postgres;' -U postgres