---
## create ansible user
  - name: User ansible creation
    user: name=ideam password={{ password }} groups=sudo

  - name: Set Bash for ansible ssh session
    command: usermod -s /bin/bash ideam
